
title: Deirdre Loughnan
email: deirdre [dot] loughnan [at] ubc [dot] ca
description: >- # this means to ignore newlines until "baseurl:"
  Zoology Department | UBC | Hakai Research Institute
# baseurl: "/DeirdreLoughnan" # the subpath of your site, e.g. /blog


# Build settings

theme: minima


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
